CREATE PROC [dbo].[usp_msft_fwk_wpa_ext_tbl_dataload] AS
BEGIN

	IF EXISTS ( SELECT * FROM sys.external_tables WHERE object_id = OBJECT_ID('csv.wpa') )
		DROP EXTERNAL TABLE [csv].[wpa]
	
	CREATE EXTERNAL TABLE [csv].[wpa]
	( 
		[PersonId] [nvarchar](255)  NULL,
		[Date] [varchar](10)  NULL,
		[Emails_sent_to_50_or_more_recipients] [float]  NULL,
		[Emails_sent_11_to_50_recipients] [float]  NULL,
		[Emails_sent_6_to_10_recipients] [float]  NULL,
		[Emails_sent_2_to_5_recipients] [float]  NULL,
		[Emails_sent_1_recipient] [float]  NULL,
		[All_hands_recurring_meeting_hours] [float]  NULL,
		[Workshop_recurring_meeting_hours] [float]  NULL,
		[Bloated_recurring_meeting_hours] [float]  NULL,
		[Lengthy_recurring_meeting_hours] [float]  NULL,
		[Status_update_recurring_meeting_hours] [float]  NULL,
		[Decision_making_recurring_meeting_hours] [float]  NULL,
		[One_on_one_recurring_meeting_hours] [float]  NULL,
		[Total_unscheduled_calls] [float]  NULL,
		[Total_scheduled_calls] [float]  NULL,
		[Working_hours_in_unscheduled_calls] [float]  NULL,
		[Working_hours_in_scheduled_calls] [float]  NULL,
		[After_hours_in_unscheduled_calls] [float]  NULL,
		[After_hours_in_scheduled_calls] [float]  NULL,
		[Unscheduled_Call_hours] [float]  NULL,
		[Scheduled_Call_hours] [float]  NULL,
		[Recurring_or_regular_meeting_hours] [float]  NULL,
		[Status_update_review_meeting_hours] [float]  NULL,
		[All_hands_meeting_hours] [float]  NULL,
		[Workshop_meeting_hours] [float]  NULL,
		[Bloated_meeting_hours] [float]  NULL,
		[Lengthy_meeting_hours] [float]  NULL,
		[Status_update_meeting_hours] [float]  NULL,
		[Decision_making_meeting_hours] [float]  NULL,
		[One_on_one_meeting_hours] [float]  NULL,
		[Meeting_hours_more_than_2_hours] [float]  NULL,
		[Meeting_hours_1_to_2_hours] [float]  NULL,
		[Meeting_hours_1_hour] [float]  NULL,
		[Meeting_hours_31_to_59_min] [float]  NULL,
		[Meeting_hours_30_min_or_less] [float]  NULL,
		[Meeting_hours_for_19_or_more_attendees] [float]  NULL,
		[Meeting_hours_for_9_to_18_attendees] [float]  NULL,
		[Meeting_hours_for_3_to_8_attendees] [float]  NULL,
		[Meeting_hours_for_2_attendees] [float]  NULL,
		[Workweek_span] [float]  NULL,
		[Working_hours_instant_messages] [float]  NULL,
		[Working_hours_in_calls] [float]  NULL,
		[Working_hours_email_hours] [float]  NULL,
		[Working_hours_collaboration_hours] [float]  NULL,
		[Total_focus_hours] [float]  NULL,
		[Total_emails_sent_during_meeting] [float]  NULL,
		[Total_calls] [float]  NULL,
		[Time_in_self_organized_meetings] [float]  NULL,
		[Redundant_meeting_hours__organizational_] [float]  NULL,
		[Redundant_meeting_hours__lower_level_] [float]  NULL,
		[Open_2_hour_blocks] [float]  NULL,
		[Open_1_hour_block] [float]  NULL,
		[Networking_outside_organization] [float]  NULL,
		[Networking_outside_company] [float]  NULL,
		[Multitasking_meeting_hours] [float]  NULL,
		[Meetings_with_skip_level] [float]  NULL,
		[Meetings_with_manager_1_on_1] [float]  NULL,
		[Meetings_with_manager] [float]  NULL,
		[Meetings] [float]  NULL,
		[Meeting_hours_with_skip_level] [float]  NULL,
		[Meeting_hours_with_manager_1_on_1] [float]  NULL,
		[Meeting_hours_with_manager] [float]  NULL,
		[Meeting_hours_during_working_hours] [float]  NULL,
		[Meeting_hours] [float]  NULL,
		[Manager_coaching_hours_1_on_1] [float]  NULL,
		[Low_quality_meeting_hours] [float]  NULL,
		[Internal_network_size] [float]  NULL,
		[Instant_messages_sent] [float]  NULL,
		[Instant_message_hours] [float]  NULL,
		[Generated_workload_meetings_organized] [float]  NULL,
		[Generated_workload_meeting_hours] [float]  NULL,
		[Generated_workload_meeting_attendees] [float]  NULL,
		[Generated_workload_instant_messages_recipients] [float]  NULL,
		[Generated_workload_instant_messages_hours] [float]  NULL,
		[Generated_workload_email_recipients] [float]  NULL,
		[Generated_workload_email_hours] [float]  NULL,
		[Generated_workload_calls_organized] [float]  NULL,
		[Generated_workload_call_participants] [float]  NULL,
		[Generated_workload_call_hours] [float]  NULL,
		[External_network_size] [float]  NULL,
		[Emails_sent] [float]  NULL,
		[Email_hours] [float]  NULL,
		[Conflicting_meeting_hours] [float]  NULL,
		[Collaboration_hours_external] [float]  NULL,
		[Collaboration_hrs] [float]  NULL,
		[Call_hours] [float]  NULL,
		[After_hours_meeting_hours] [float]  NULL,
		[After_hours_instant_messages] [float]  NULL,
		[After_hours_in_calls] [float]  NULL,
		[After_hours_email_hours] [float]  NULL,
		[After_hours_collaboration_hours] [float]  NULL,
		[Domain] [nvarchar](255)  NULL,
		[FunctionType] [nvarchar](255)  NULL,
		[LevelDesignation] [nvarchar](255)  NULL,
		[Layer] [float]  NULL,
		[Region] [nvarchar](255)  NULL,
		[Organization] [nvarchar](255)  NULL,
		[zId] [nvarchar](255)  NULL,
		[HireDate] [varchar](10)  NULL,
		[attainment] [nvarchar](255)  NULL,
		[SupervisorIndicator] [nvarchar](255)  NULL,
		[Number_of_directs] [float]  NULL,
		[ADO_PersonSK] [nvarchar](255)  NULL,
		[ADO_PersonIndicator] [bit]  NULL,
		[TimeZone] [nvarchar](255)  NULL,
		[HourlyRate] [float]  NULL,
		[IsInternal] [bit]  NULL,
		[IsActive] [bit]  NULL,
		[WorkingStartTimeSetInOutlook] [nvarchar](255)  NULL,
		[WorkingEndTimeSetInOutlook] [nvarchar](255)  NULL,
		[WorkingDaysSetInOutlook] [nvarchar](255)  NULL
	)
	WITH 
		(	DATA_SOURCE = [wpa_csv], 
			LOCATION = '/classification/wpa/wpa.csv',  
			FILE_FORMAT = [QuotedCsvWithHeader]
		 )
	
END